build:
  nodes:
    analysis:
      environment:
        php:
          version: 7.4.9
          pecl_extensions:
            - redis
      services:
        redis: 6
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths:
    - "tests/"
    - "build/"
  dependency_paths:
    - "vendor/"

tools:
    external_code_coverage:
        timeout: 2100 # Timeout in seconds.
