name: CI

on:
    push:
    pull_request:
    release:
        types:
            - published

jobs:
    php-tests:
        runs-on: ${{ matrix.os }}

        services:
          redisgraph:
            image: redislabs/redisgraph:latest
            ports:
              - 6379:6379

        strategy:
            fail-fast: false
            matrix:
                php: [8.4]
                laravel: [10.*, 11.*, 12.*]
                os: [ubuntu-latest]
                coverage: [none]
                include:
                    - php: 8.4
                      laravel: 12.*
                      os: ubuntu-latest
                      coverage: xdebug

        name: '[P${{ matrix.php }}] [L${{ matrix.laravel }}] [${{ matrix.coverage }}]'

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring json openssl xdebug redis intl
                  ini-values: memory_limit=-1
                  tools: composer:v2
                  coverage: ${{ matrix.coverage }}
              env:
                  update: true

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: vendor
                  key: ${{ matrix.os }}-${{ matrix.php }}-${{ matrix.laravel }}-vendor-${{ hashFiles('**/composer.lock') }}

            - name: Install Dependencies
              uses: ramsey/composer-install@v3

            - name: Execute tests (Unit and Feature tests) via PHPUnit
              if: matrix.coverage == 'none'
              run: composer test

            - name: Run code style check
              if: matrix.coverage == 'xdebug'
              run: composer check

            - name: Run code analyze
              if: matrix.coverage == 'xdebug'
              run: composer analyze

            - name: Execute tests (Unit and Feature tests) via PHPUnit
              if: matrix.coverage == 'xdebug'
              run: composer test-ci

            - name: Upload coverage reports to Codecov
              if: matrix.coverage == 'xdebug'
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: ${{ github.repository }}

            - name: Upload test results to Codecov
              if: matrix.coverage == 'xdebug'
              uses: codecov/test-results-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: ${{ github.repository }}
